export const CONSTANTS = {
	YES: 1,
	NO: 0,
	HTTP_RESPONSE: {
		SUCCESS: 200,
		BAD_REQUEST: 400,
		UNAUTHORIZED: 401,
		INPROCESSIBLE: 422,
		SERVER_ERROR: 500,
	},
	ERROR_TYPE: {
		TOAST: "TOAST",
		ALERT: "ALERT"
	},
	MOVIE_LIST_TYPE: {
		CURRENTLY_PLAYED: "currently-played",
		COMING_SOON: "coming-soon"
	}
}

