const ALERT_CONSTANTS = {
	SUCCESS: 'ALERT_SUCCESS',
	ERROR: 'ALERT_ERROR',
	SECONDARY: 'ALERT_SECONDARY',
	CLEAR: 'ALERT_CLEAR',
	WARNING: 'ALERT_WARNING',
}

const HOME_CONSTANTS = {
	HOMEPAGE_META: {
		REQUEST: 'HOMEPAGE_METADATA_REQUEST',
		SUCCESS: 'HOMEPAGE_METADATA_SUCCESS',
		FAILURE: 'HOMEPAGE_METADATA_FAILURE',
	},
	HOMEPAGE: {
		REQUEST: 'HOMEPAGE_REQUEST',
		SUCCESS: 'HOMEPAGE_SUCCESS',
		FAILURE: 'HOMEPAGE_FAILURE',
	},
}

export {
	ALERT_CONSTANTS,
	HOME_CONSTANTS,
}